/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  Contract,
  ContractTransaction,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  BytesLike,
  ContractInterface,
  Overrides
} from "ethers";

export class FundsManager extends Contract {
  functions: {
    reversePlasma(): Promise<{
      0: string;
    }>;

    tokenOnETH(): Promise<{
      0: string;
    }>;
  };

  reversePlasma(): Promise<string>;

  tokenOnETH(): Promise<string>;

  filters: {};

  estimateGas: {
    reversePlasma(): Promise<BigNumber>;

    tokenOnETH(): Promise<BigNumber>;
  };
}
