/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  Contract,
  ContractTransaction,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  BytesLike,
  ContractInterface,
  Overrides,
} from 'ethers';

export class FundsManager extends Contract {
  functions: {
    plasmaManager(): Promise<{
      0: string;
    }>;

    token(): Promise<{
      0: string;
    }>;
  };

  plasmaManager(): Promise<string>;

  token(): Promise<string>;

  filters: {};

  estimateGas: {
    plasmaManager(): Promise<BigNumber>;

    token(): Promise<BigNumber>;
  };
}
